import type { Metadata } from "next";

import "./globals.css";


import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/shared/footer";

import Header from "@/components/shared/header";
import { ThemeProvider } from "@/components/theme-provider";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning translate="no" >
      <body
        className={`antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <div className="px-4 sm:px-14 md:px-24 lg:px-32 pt-[80px]">
            {children}
          </div>
          <Footer />
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
